package corbaConversion;


/**
* corbaConversion/IConversionRemote.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Conversion.idl
* Thursday, 30 November 2023 08:52:26 o'clock WAT
*/


// Définition de l'interface IConversionRemote
public interface IConversionRemote extends IConversionRemoteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IConversionRemote
